#!/usr/bin/env bash
set -euo pipefail

# ai-config sync script
# Usage:
#   sync.sh [options] <target-repo-path>
# Options:
#   --force     Sync without confirmation
#   --dry-run   Show what would be synced without copying

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SHARED_DIR="${SCRIPT_DIR}/shared"
TEMPLATES_DIR="${SCRIPT_DIR}/templates"

# Parse arguments
FORCE=false
DRY_RUN=false
while [[ "${1:-}" == --* ]]; do
  case "$1" in
    --force)   FORCE=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

if [[ $# -lt 1 ]]; then
  echo "Usage:" >&2
  echo "  $0 [options] <target-repo-path>" >&2
  echo "  Options:" >&2
  echo "    --force     Sync without confirmation" >&2
  echo "    --dry-run   Show what would be synced without copying" >&2
  exit 1
fi

TARGET_DIR="$1"

if [[ ! -d "${TARGET_DIR}/.git" ]]; then
  echo "Error: ${TARGET_DIR} is not a git repository" >&2
  exit 1
fi

# Collect shared files and check for changes
shared_new=()
shared_changed=()
shared_unchanged=()

if [[ -d "${SHARED_DIR}" ]]; then
  while IFS= read -r src_path; do
    rel_path="${src_path#"${SHARED_DIR}/"}"
    dest_path="${TARGET_DIR}/${rel_path}"

    if [[ ! -f "${dest_path}" ]]; then
      shared_new+=("${rel_path}")
    elif ! diff -q "${src_path}" "${dest_path}" > /dev/null 2>&1; then
      shared_changed+=("${rel_path}")
    else
      shared_unchanged+=("${rel_path}")
    fi
  done < <(find "${SHARED_DIR}" -type f | sort)
fi

# Collect template files
template_new=()
template_skip=()

if [[ -d "${TEMPLATES_DIR}" ]]; then
  while IFS= read -r src_path; do
    rel_path="${src_path#"${TEMPLATES_DIR}/"}"
    dest_path="${TARGET_DIR}/${rel_path}"

    if [[ ! -f "${dest_path}" ]]; then
      template_new+=("${rel_path}")
    else
      template_skip+=("${rel_path}")
    fi
  done < <(find "${TEMPLATES_DIR}" -type f | sort)
fi

# Display summary
echo "Shared files:"
for f in "${shared_new[@]+"${shared_new[@]}"}"; do
  echo "  new:       ${f}"
done
for f in "${shared_changed[@]+"${shared_changed[@]}"}"; do
  echo "  changed:   ${f}"
done
for f in "${shared_unchanged[@]+"${shared_unchanged[@]}"}"; do
  echo "  unchanged: ${f}"
done

echo ""
echo "Templates:"
for f in "${template_new[@]+"${template_new[@]}"}"; do
  echo "  new:  ${f}"
done
for f in "${template_skip[@]+"${template_skip[@]}"}"; do
  echo "  skip: ${f} (already exists)"
done

# Count actionable items
total_copy=$(( ${#shared_new[@]} + ${#shared_changed[@]} + ${#template_new[@]} ))

if [[ ${total_copy} -eq 0 ]]; then
  echo ""
  echo "Nothing to sync."
  exit 0
fi

echo ""
echo "${total_copy} file(s) to copy (${#shared_new[@]} new shared, ${#shared_changed[@]} changed shared, ${#template_new[@]} new templates)"

# Exit if dry-run
if [[ "${DRY_RUN}" == true ]]; then
  exit 0
fi

# Confirm unless --force
if [[ "${FORCE}" != true ]]; then
  read -r -p "Overwrite all / Cancel? [Y/n] " answer
  if [[ "${answer}" =~ ^[Nn] ]]; then
    echo "Cancelled."
    exit 0
  fi
fi

# Copy shared files (new + changed)
for f in "${shared_new[@]+"${shared_new[@]}"}" "${shared_changed[@]+"${shared_changed[@]}"}"; do
  [[ -z "${f}" ]] && continue
  src="${SHARED_DIR}/${f}"
  dest="${TARGET_DIR}/${f}"
  mkdir -p "$(dirname "${dest}")"
  cp "${src}" "${dest}"
  echo "  copy: ${f}"
done

# Copy template files (new only)
for f in "${template_new[@]+"${template_new[@]}"}"; do
  [[ -z "${f}" ]] && continue
  src="${TEMPLATES_DIR}/${f}"
  dest="${TARGET_DIR}/${f}"
  mkdir -p "$(dirname "${dest}")"
  cp "${src}" "${dest}"
  echo "  copy: ${f} (template)"
done

# Write sync metadata
METADATA_FILE="${TARGET_DIR}/.claude/.ai-config-sync"
mkdir -p "$(dirname "${METADATA_FILE}")"
COMMIT_HASH="$(git -C "${SCRIPT_DIR}" rev-parse --short HEAD)"
SYNCED_AT="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
cat > "${METADATA_FILE}" <<EOF
# Auto-generated by ai-config sync.sh
commit: ${COMMIT_HASH}
synced_at: ${SYNCED_AT}
EOF
echo "  write: .claude/.ai-config-sync"

echo ""
echo "Sync complete."
